[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "milkcrate"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["pandas", "scikit-learn>=1.3,<1.6", "joblib", "streamlit>=1.34"]

[tool.setuptools]
packages = ["milkcrate"]
